[colors.bright]
black = "0x262626"
blue = "0xb8bcd6"
cyan = "0xb8d6d3"
green = "0xbcd6b8"
magenta = "0xd3b8d6"
red = "0xd6b8bc"
white = "0xffffff"
yellow = "0xd6d3b8"

[colors.normal]
black = "0x000000"
blue = "0x6d74ac"
cyan = "0x6daca4"
green = "0x74ac6d"
magenta = "0xa46dac"
red = "0xac6d74"
white = "0xe6e6e6"
yellow = "0xaca46d"

[colors.primary]
background = "0x09111a"
foreground = "0xd9e6f2"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font]
size = 9

[window]
opacity = 0.7
